services:
  - type: web
    name: portfolio-backend
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py migrate
    startCommand: cd backend && gunicorn portfolio.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "*"
